-- ============================================================
-- SCRIPT COMPLETO: Actualizar equipo_id de todos los jugadores
-- Segunda Andaluza - 543 jugadores en 16 equipos
-- Ejecutar en Supabase SQL Editor
-- ============================================================

-- Migración 014: CHICLANA IND. C.F. (32 jugadores)
UPDATE public.jugadores SET equipo_id = 'f2ca27e7-2f45-4906-9f4b-a397632219f6'
WHERE (nombre, apellidos) IN (
  ('Adán', 'Medina Quirós'),
  ('Fran', 'Morales Bernal'),
  ('Ivan', 'Callealta Sánchez'),
  ('Borja', 'Hermida Rodrigo'),
  ('Enrique', 'Brenes Jiménez'),
  ('Fran', 'Jiménez Legupin'),
  ('Jose', 'González Pérez'),
  ('Marcos', 'Aragon Hermoso'),
  ('Raúl', 'López Arsenal'),
  ('Adri', 'Domínguez Roa'),
  ('Alba', 'Alba Vela'),
  ('Álvaro', 'Hurtado Rodríguez'),
  ('Clemente', 'Gómez Oliva'),
  ('Cristian', 'Velázquez Flores'),
  ('Esteban', 'Sánchez Marín'),
  ('Guillermo', 'Hahn Bergantiño'),
  ('Javi', 'Ortega Belizón'),
  ('Juanca', 'Velázquez Magariño'),
  ('Manuel', 'Pinto Reina'),
  ('Miguel', 'Betanzo Espada'),
  ('Ruben', 'Moreno Flores'),
  ('Álvaro', 'Moreno Aguilar'),
  ('Antonio', 'Ortiz Valverde'),
  ('Cris', 'González Betanzos'),
  ('Esteban', 'Marín Domínguez'),
  ('Jesús', 'Periñán Aragón'),
  ('Luis', 'Cebada Fernández'),
  ('Mario', 'Callealta Sánchez'),
  ('Óscar', 'Rodríguez Galvín'),
  ('Pablo', 'Rodríguez Espinosa'),
  ('Viki', 'Cabeza de Vaca Aragón'),
  ('Yaroslav', 'Pukha')
);

-- Migración 015: C.D. EL TORNO 2009 (35 jugadores)
UPDATE public.jugadores SET equipo_id = '18f07e59-e214-47ca-b99c-cbf2133a0ef9'
WHERE (nombre, apellidos) IN (
  ('Adrián', 'García Carmona'),
  ('Chico', 'Martin Noble'),
  ('Pablo Antonio', 'Beltran Rojas'),
  ('Adrian', 'Cepero Lebron'),
  ('Diego', 'García Castro'),
  ('Floren', 'Roman Garcia de Veas'),
  ('Jorge', 'Sánchez Diaz'),
  ('Juanito', 'Mesa Macias'),
  ('Manolete', 'Perez Olea'),
  ('Rafa', 'González Ramírez'),
  ('Rodri', 'Rodríguez Rodríguez'),
  ('Rubén', 'Olid Vega'),
  ('Vicente', 'Fernandez Ceballos'),
  ('Yuni', 'Moreno Seda'),
  ('Antonio', 'Barroso Heredia'),
  ('Antonio', 'Medina López'),
  ('Caba', 'Cabanillas Aldón'),
  ('Javi', 'Martin Pacheco'),
  ('Juan Antonio', 'García Morón'),
  ('Juan', 'Benítez Ramos'),
  ('Poyatos', 'Poyatos Dorado'),
  ('Roque', 'Durán Lebrón'),
  ('Rubén', 'Galiano Braza'),
  ('Yoel', 'Cabanillas Aldon'),
  ('Alberto', 'Santos Postigo'),
  ('Alex', 'Fernández Vilches'),
  ('Félix', 'Ramirez Barba'),
  ('Félix', 'Salguero Infante'),
  ('Gámez', 'Gámez Reina'),
  ('Juanjo', 'Ruiz Navas'),
  ('Lamela', 'Fernández Lamela'),
  ('Morales', 'Morales Avila'),
  ('Óscar', 'Gálvez Jiménez'),
  ('Robe', 'Ruiz Lebrón'),
  ('Yeray', 'Morales García')
);

-- Migración 016: C.D. SAN ROQUE (38 jugadores)
UPDATE public.jugadores SET equipo_id = 'a80664d3-1515-42c3-8b2a-619b401d1f5d'
WHERE (nombre, apellidos) IN (
  ('Alex', 'García Fernández'),
  ('David', 'Jiménez Polanco'),
  ('Fran', 'Rodríguez Bellido'),
  ('Rubén', 'Román Fernández'),
  ('Víctor', 'Ayala Orrillo'),
  ('Álex', 'Benítez Martín'),
  ('Banderas', 'Banderas Murillo'),
  ('Chechu', 'Calvo Ferrer'),
  ('Dani', 'Martín Delgado'),
  ('Fran', 'Díaz Malia'),
  ('José Augusto', 'Casanova Turrillo'),
  ('Miranda', 'Miranda Llaveta'),
  ('Moto', 'López Ferrer'),
  ('Rubén Alconchel', 'Alconchel Oliva'),
  ('Toledo', 'Fernández Toledo'),
  ('Adrián', 'Furné Gutiérrez'),
  ('Alejandro', 'Ferra Lara'),
  ('Álex', 'García Carrillo'),
  ('Álex', 'González Buendía'),
  ('Andrés', 'Sánchez Sereno'),
  ('Carlos', 'Ruiz Corbacho'),
  ('Isma', 'Furne Gutiérrez'),
  ('Jaime', 'Rodriguez Navas'),
  ('Luis', 'De la Luz Pelayo Hoyos'),
  ('Miguel', 'Ortiz Merino'),
  ('Otero', 'Otero Domínguez'),
  ('Tamarit', 'Tamarit García'),
  ('Zalayeta', 'Zalayeta'),
  ('Abel', 'Ruiz Cervan'),
  ('Abraham', 'Lobo López'),
  ('Álex', 'García Sanjorge'),
  ('Ezequiel', 'Estigarribia Velázquez'),
  ('Juanma', 'Ocaña Ruiz'),
  ('Kevin', 'Peñalosa Ruíz'),
  ('Ledesma', 'Ledesma Carrillo'),
  ('Niko', 'Pereira Pina'),
  ('Pino', 'Pino Rivas'),
  ('Sergio', 'Palma García')
);

-- Migración 017: REAL BALOMPEDICA LINENSE (40 jugadores)
UPDATE public.jugadores SET equipo_id = '131bc731-4c8e-4249-a341-041901d3433d'
WHERE (nombre, apellidos) IN (
  ('Álex', 'Orozco Gavilán'),
  ('Daniel', 'Quintero Millán'),
  ('Diego', 'Mercado Peinado'),
  ('Miguel Ángel', 'Álvarez Rubio'),
  ('Adri', 'Jiménez Rodríguez'),
  ('Aguilera', 'Aguilera Martín'),
  ('Alberto', 'Gómez Báez'),
  ('Álex', 'Díaz Sibajas'),
  ('Carlos', 'Del Pino Rios'),
  ('Francis', 'Pecino Alconchel'),
  ('Germán', 'Ruiz González de Canales'),
  ('Henry', 'Yepes Ayala'),
  ('Ilias', 'Nam el Hamdaoui'),
  ('Jairo', 'Piñero Muñoz'),
  ('Manu', 'Fajarne Cervera'),
  ('Moustapha', 'Seck Dione'),
  ('Raúl', 'Fajarne Cervera'),
  ('Adrián', 'Melgar Guerrero'),
  ('Anuar', 'el Amiri Sammama'),
  ('Hoyo', 'Sánchez Hoyo'),
  ('Javi', 'Doncel Benitez'),
  ('Jesús', 'Méndez Ávalo'),
  ('Jona', 'Morente Martín'),
  ('Marcos', 'Fernández Cabrera'),
  ('Portela', 'Gómez Portela'),
  ('Samu', 'Merino Cervera'),
  ('Sergio', 'Suárez Corrales'),
  ('Achkra', 'Achkra'),
  ('Álvaro', 'Ríos Sore'),
  ('Jesuli', 'Piñer Espinosa'),
  ('Joaquin', 'González Luque'),
  ('Jonathan', 'Arroyo Santiago'),
  ('José', 'Tomillero Almida'),
  ('Joselu', 'Avilés Nabo'),
  ('Leonardo', 'Blasco de Freitas'),
  ('Manuel', 'Quintero Millán'),
  ('Rubén', 'Fernández Ruiz'),
  ('Salvari', 'Arguez Oliva'),
  ('Victory', 'Gigi John')
);

-- Migración 018: JUVENTUD SANLUQUEÑA A.D. (27 jugadores)
UPDATE public.jugadores SET equipo_id = '2c756d8c-bb4d-4074-b633-051594024eb1'
WHERE (nombre, apellidos) IN (
  ('Alejandro', 'Cáceres Lara'),
  ('Nacho', 'Pérez Seco'),
  ('Núa', 'Senra Ibañez'),
  ('Diop', 'Diop'),
  ('Estrugo', 'Estrugo González'),
  ('Ezequiel', 'Romero Becerra'),
  ('Pablo', 'López Rodríguez'),
  ('Piti', 'González Álvarez'),
  ('Salvi', 'Pozo Monge'),
  ('Sergio', 'Castellano Carrasco'),
  ('Adam', 'Jiménez Martínez'),
  ('Alex', 'Morales Sanchez'),
  ('Camacho', 'Camacho Rivera'),
  ('Fran', 'Domínguez Cruz'),
  ('Jesús', 'Rendón Garcia'),
  ('José', 'Pérez Seco'),
  ('Moy', 'Núñez García'),
  ('Remo', 'Jiménez Rangel'),
  ('Brando', 'Jiménez Vidal'),
  ('Christian', 'Aznar Fernández'),
  ('Gálvez', 'Gálvez Rodríguez'),
  ('Josemi', 'Sánchez Cadena'),
  ('Luismi', 'Ibáñez García'),
  ('Mario', 'Mena Pipio'),
  ('Marrufo', 'Marrufo Pérez'),
  ('Oviedo', 'Oviedo Porta'),
  ('Tamayo', 'Tamayo Clavijo')
);

-- Migración 019: JEDULA C.D. (36 jugadores)
UPDATE public.jugadores SET equipo_id = 'e9c8b453-3af9-4f8a-8680-fc9738ab851a'
WHERE (nombre, apellidos) IN (
  ('Álvaro', 'Mateos Pantoja'),
  ('Hugo', 'Gil García'),
  ('José', 'García López'),
  ('Juanmi', 'Casas Cote'),
  ('Manuel', 'Roldan Muñoz'),
  ('Paco', 'Pajuelo De Los Reyes'),
  ('Chato', 'Hernández Garcia'),
  ('Dani', 'Goma Rosales'),
  ('Juandi', 'Gil Carrera'),
  ('Julio', 'Benitez Orozco'),
  ('Marcos', 'Madrena Jiménez'),
  ('Miguel', 'Enríquez Barragán'),
  ('Rafa', 'Benítez Castrelo'),
  ('Rafael', 'Muñoz Cuevas'),
  ('Raúl', 'Aguilar Hierro'),
  ('Raúl', 'González Santos'),
  ('Zakaria', 'Assadi Boukhari'),
  ('Adrián', 'Galloso Martínez'),
  ('Isidoro', 'Gallego Iglesias'),
  ('Jesús', 'Rondán Archidona'),
  ('Manuel', 'Medina Ruiz'),
  ('Marcos', 'Segovia Macías'),
  ('Migue', 'Artal Pacheco'),
  ('Moy', 'Torres Amaya'),
  ('Pablo', 'Gil Cebrián'),
  ('Pablo', 'Valle Avecilla'),
  ('Alejandro', 'Pineda Cabrera'),
  ('Elio', 'Muñoz Medina'),
  ('Girón', 'Girón De La Barrera'),
  ('Hita', 'Hita Jiménez'),
  ('José', 'Barba González'),
  ('Juan', 'Olivera López'),
  ('Marcos', 'Camarena Ramírez'),
  ('Omar', 'Aguilar Mahimda'),
  ('Rivero', 'Rivero Gargallo'),
  ('Rooney', 'Ortega Aleu')
);

-- Migración 020: OLVERA C.D. (31 jugadores)
UPDATE public.jugadores SET equipo_id = '1f1a189f-3f5d-4527-875f-cc14b408189b'
WHERE (nombre, apellidos) IN (
  ('Francisco', 'Ortega Castro'),
  ('Germán', 'Bocanegra Albarrán'),
  ('Rubén', 'Periáñez Sacie'),
  ('Zarzu', 'Zarzuela Bocanegra'),
  ('Antonio', 'Escalante Escalante'),
  ('Dani', 'Burgos Calderón'),
  ('Galindo', 'Rubiales Galindo'),
  ('Hugo', 'Villalba Toledo'),
  ('Iván', 'Mulero Escalona'),
  ('MACA', 'Jiménez Saborido'),
  ('Mario', 'Pérez Márquez'),
  ('Melchor', 'Pérez Mulero'),
  ('Álvaro', 'Troya Periáñez'),
  ('Ángel', 'Porras Gutiérrez'),
  ('Caico', 'Casanueva Gómez'),
  ('Diego', 'Cabrera Mesa'),
  ('Pablo', 'Gómez Cabeza'),
  ('Paradas', 'Paradas Perez'),
  ('Ricardo', 'Cabrera Jiménez'),
  ('Trilli', 'Perez Barrera'),
  ('Alex', 'Bocanegra Párraga'),
  ('Alfonso', 'Perez Caravaca'),
  ('Álvaro', 'Zambrana Gómez'),
  ('Anas', 'El Fkih Mira'),
  ('Charli', 'Pérez Jiménez'),
  ('Morales', 'Morales Cabeza'),
  ('Óscar', 'Márquez Zamudio'),
  ('Rubén', 'Jiménez Carreño'),
  ('Rubén', 'Mancio Paradas'),
  ('Samuel', 'Cabeza Menacho'),
  ('Xesco', 'Bocanegra Párraga')
);

-- Migración 021: CHIPIONA C.F. (32 jugadores)
UPDATE public.jugadores SET equipo_id = '386ef181-4ec5-4079-aa9a-35597f473aba'
WHERE (nombre, apellidos) IN (
  ('Andres', 'Gomez Parra'),
  ('Cabeza', 'Cabeza García'),
  ('Dani', 'Montalban Montiel'),
  ('Manu', 'Rodríguez Porta'),
  ('Martínez', 'Martínez Vidal'),
  ('Nico', 'Fernández Bustinduy'),
  ('Blanco', 'Blanco Valdés'),
  ('Chote', 'Peña Carpio'),
  ('Dani', 'Pérez Porras'),
  ('Dani', 'Rodríguez Ruiz'),
  ('Dani', 'Garcia Vazquez'),
  ('Iván', 'Caballero Lucena'),
  ('Jesús', 'Del Moral Porras'),
  ('Miranda', 'Miranda Pérez de la Lastra'),
  ('Rivaldo', 'Alconchel Margarida'),
  ('TROYI', 'PÉREZ TROYANO'),
  ('Abraham', 'López Lorenzo'),
  ('Borja', 'Peinado Verano'),
  ('David', 'Tirado Bernal'),
  ('José', 'García Leal'),
  ('Joud', 'Joud López'),
  ('Juanma', 'Benitiz Quiros'),
  ('Leandro', 'Jiménez Acaso'),
  ('Sergio', 'Solís Castaño'),
  ('David', 'Lorenzo Santos'),
  ('Eze', 'Martín Rúa'),
  ('Florido', 'Florido Caro'),
  ('Migue', 'González Pajarón'),
  ('Petaca', 'Grilo Ruiz'),
  ('Ricky', 'Cos Acuña'),
  ('Samu', 'Naval Castaño'),
  ('Simón', 'Perales Ramos')
);

-- Migración 022: U.D. TESORILLO (46 jugadores)
UPDATE public.jugadores SET equipo_id = 'fb374d39-3883-46ee-8af1-88b61f22bdaa'
WHERE (nombre, apellidos) IN (
  ('Álvaro', 'Torres Sánchez'),
  ('David', 'Mena Maldonado'),
  ('Juan', 'Ruiz Sánchez'),
  ('Alejandro', 'Troya López'),
  ('Yeray', 'Espada Bañasco'),
  ('Bachir', 'Bennor Selva'),
  ('Javier', 'Collado Sarría'),
  ('Federico', 'Guerreiro Martín'),
  ('Juan', 'García Rodríguez'),
  ('Álvaro', 'Caballero Vilches'),
  ('Hector', 'Sadobe'),
  ('Jorge', 'Domínguez García'),
  ('Salvador', 'Mesa Sánchez'),
  ('Diego', 'González Pachón'),
  ('Juan', 'Rubio Manzano'),
  ('Enrique', 'del Alcázar Delgado'),
  ('Alvaro', 'Requena Mena'),
  ('Sergio', 'Tirado Sánchez'),
  ('Alberto', 'Lopez Morilla'),
  ('Alioune', 'Ndiaye Gonzalez'),
  ('Ignacio', 'Caballero Ginés'),
  ('Cristian', 'Guerrero Alconchel'),
  ('José', 'Alamino Segovia'),
  ('David', 'Mancera Garcia'),
  ('Miguel', 'Salas Gavira'),
  ('Francisco', 'Moreno Donda'),
  ('Pablo', 'Torres Lobato'),
  ('Pedro', 'Martin Mateo'),
  ('Juan', 'Reine Pérez'),
  ('Sergiu', 'Marian Oprea'),
  ('José', 'González Morales'),
  ('Adrián', 'Rodríguez Rodríguez'),
  ('Antonio', 'Aguirre Aguirre'),
  ('Fernando', 'Cuesta Bakouri'),
  ('Ibrahim', 'Khbiyez Laariara'),
  ('Isaac', 'Pérez Macías'),
  ('Jacob', 'Arguello Ubillus'),
  ('Juan', 'Romero Gil'),
  ('Sergio', 'Ginés Pérez'),
  ('Lorenzo', 'Micha Eyang'),
  ('Manuel', 'Marín Barranco'),
  ('Francisco', 'Rios Rivera'),
  ('Francisco', 'Pérez Cano'),
  ('Abrahan', 'Marchante Gómez'),
  ('Roberto', 'Nahuel Mena'),
  ('Sadek', 'Sadek Mohamed')
);

-- Migración 023: C.D. UBRIQUE (38 jugadores)
UPDATE public.jugadores SET equipo_id = 'd96afce6-7f39-4222-abc5-e778836d6d17'
WHERE (nombre, apellidos) IN (
  ('Cristian', 'Cadenas Ortega'),
  ('David', 'López Núñez'),
  ('Fernando', 'Sánchez Chacón'),
  ('Melli', 'Ordoñez Capote'),
  ('Rodrigo', 'Rosado Yáñez'),
  ('Álvaro', 'Coronel Valle'),
  ('BENY', 'Benitiz Angulo'),
  ('Daniel', 'Bohorquez Gómez'),
  ('David', 'Cantos Fernández'),
  ('Francisco', 'Llucía Barragán'),
  ('Francisco', 'Gago González'),
  ('José', 'López García'),
  ('Iván', 'Sánchez Moscoso'),
  ('Josue', 'Pinilla Vargas'),
  ('Jose', 'Lamela Rodriguez'),
  ('Manuel', 'Figueroa Roman'),
  ('Manuel', 'Calvo Sevilla'),
  ('Mario', 'Chacón Rios'),
  ('Carlos', 'Mena Arce'),
  ('Juan', 'Montedeoca Fernandez'),
  ('Álvaro', 'Macías Moreno'),
  ('Aníbal', 'Rodriguez Vazquez'),
  ('Antonio', 'Coveñas Sánchez'),
  ('Arturo', 'de Oria Blanco'),
  ('Francisco', 'Ruiz Sotomayor Galvin'),
  ('Francisco', 'Fernández Rivero'),
  ('Fernando', 'Sánchez Jiménez'),
  ('Álvaro', 'Garcés Dominguez'),
  ('Francisco', 'Pérez López'),
  ('Pedro', 'Rodríguez Salguero'),
  ('Raúl', 'Flores González'),
  ('Adriano', 'Corrales Pérez'),
  ('Alejandro', 'García Miranda'),
  ('Cristian', 'Mateos Salguero'),
  ('Lucas', 'Moscoso Pérez'),
  ('Pablo', 'Vega Muñoz'),
  ('Agustín', 'Zeballos Delfino'),
  ('Ismael', 'Zeballos Delfino')
);

-- Migración 024: GRUPO EMPRESA BAZAN (37 jugadores)
UPDATE public.jugadores SET equipo_id = '503aa32d-bd45-458d-bec0-9e31aa21cecf'
WHERE (nombre, apellidos) IN (
  ('Asier', 'Carrera Medina'),
  ('Daniel', 'García Baena'),
  ('Ignacio', 'Carles López'),
  ('Joaquin', 'Garcés Nieto'),
  ('Marco', 'Pipio Berea'),
  ('Ruben', 'Braza Jimenez'),
  ('Ruben', 'Braza Braza Jimenez'),
  ('Jesús', 'Aguirre García'),
  ('Camilo', 'Babilonia Navarro'),
  ('Brian', 'Herreros Fabra'),
  ('David', 'Pinedo Núñez'),
  ('Javier', 'Suárez Pimentel'),
  ('Jesús', 'Gutiérrez Gómez'),
  ('Manuel', 'Cornejo Amaya'),
  ('Jesús', 'Ochoa Barriga'),
  ('Raúl', 'Chapela López'),
  ('Raúl', 'Alias Callejón'),
  ('Samuel', 'Sarmiento Cruz'),
  ('Victor', 'León Camacho'),
  ('Adrián', 'Blanco Bozo'),
  ('Alejandro', 'Guerrero Sevillano'),
  ('Hugo', 'Ávila Marín'),
  ('Hugo', 'De la Flor Rodríguez'),
  ('Isaac', 'Rodriguez Rivero'),
  ('Javier', 'Girón Freire'),
  ('Francisco', 'Romero Pinedo'),
  ('Mario', 'Jiménez Palomino'),
  ('Matías', 'Respeto Solano'),
  ('Mauro', 'Pastor Gutiérrez'),
  ('Miguel', 'Garrido Castro'),
  ('Alberto', 'de Celis Costilla'),
  ('Alejandro', 'Collantes López'),
  ('Juan', 'Conejero Benítez'),
  ('Kevin', 'Lamela Garrido'),
  ('Miguel', 'de Alba Gallego'),
  ('Miguel', 'Pacheco Rodriguez'),
  ('Roberto', 'Viciana Rodríguez')
);

-- Migración 025: C.D. VEJER BALOMPIE (31 jugadores)
UPDATE public.jugadores SET equipo_id = '2513e544-7386-491b-9d0b-b48e5a7e0513'
WHERE (nombre, apellidos) IN (
  ('Ibra', 'Diouf'),
  ('Paulo', 'Espinosa Rubio'),
  ('Antonio', 'Gonzalez Lopez'),
  ('David', 'Donso'),
  ('David', 'Melero Vélez'),
  ('Domingo', 'González Orihuela'),
  ('Emilio', 'Durán Duarte'),
  ('Jose', 'Rivera Pérez'),
  ('Juan', 'Gómez Tello'),
  ('José', 'Lebrón Tejonero'),
  ('Mario', 'Moya Gallardo'),
  ('Antonio', 'Sánchez Pastor'),
  ('Said', 'Yahdih Mohamed Salem'),
  ('Jose', 'Alcedo Servan'),
  ('Álvaro', 'Miralles Morillo'),
  ('Christian', 'Vélez Sánchez'),
  ('Francisco', 'Relinque Galindo'),
  ('José', 'Martinez Bello'),
  ('Shodmekhr', 'Kurbanov'),
  ('Luis', 'Perez Peregrino'),
  ('Manuel', 'Rosales Garcés'),
  ('José', 'Melero Rodríguez'),
  ('Raúl', 'Rojas Relinque'),
  ('Manuel', 'Reyes Guerrero'),
  ('Abdou', 'Thiam Diouf'),
  ('Alejandro', 'Moreno Serván'),
  ('Antonio', 'Moreno Revuelta'),
  ('Antonio', 'Salado Zellat'),
  ('José', 'Melero Crespo'),
  ('Juan', 'Moreno Serván'),
  ('Oliver', 'Morales González')
);

-- Migración 026: XEREZ C.D. (33 jugadores)
UPDATE public.jugadores SET equipo_id = '19aa6989-d34f-4451-9ae4-e9024db658fd'
WHERE (nombre, apellidos) IN (
  ('Andrés', 'Canto Gómez'),
  ('Daniel', 'Jiménez Robles'),
  ('Hugo', 'Costela Aragón'),
  ('Mauricio David', 'Trujillo Marín'),
  ('Parsa', 'Baghersad Renani'),
  ('Anass', 'Latif'),
  ('Ángel', 'Campos Rodríguez'),
  ('Francisco Javier', 'Cadena González'),
  ('Daniel', 'del Ojo Sánchez'),
  ('David', 'La Chica Gómez'),
  ('Diego Fernando', 'García Aliaño'),
  ('Francisco Javier', 'Guerrero García'),
  ('Iván', 'Ramos Jimenez'),
  ('Javier', 'Cauqui Barroso'),
  ('Leo', 'Marín Bredel'),
  ('Nestor', 'Gascon Parra'),
  ('Raúl', 'Segura Galán'),
  ('Samuel', 'Arriaza Guerrero'),
  ('David', 'Figueroa Díaz'),
  ('Antonio', 'Montero Barroso'),
  ('Alberto', 'Ruiz Berdejo López'),
  ('Bako', 'Traore'),
  ('Daniel', 'Sánchez del Castillo'),
  ('Manuel', 'Gálvez Román'),
  ('Germán', 'Romero Román'),
  ('Juan', 'Landa Navarro'),
  ('Julio', 'Pineda Jiménez'),
  ('Manuel Alejandro', 'Román Holgado'),
  ('Mario', 'Garcés Ordóñez'),
  ('José', 'Conde Ortínez'),
  ('Sergio', 'Arze Méndez'),
  ('Jesús', 'Soto Yuste'),
  ('Javier', 'López Buzón')
);

-- Migración 027: JIMENA ATHLETIC CLUB C.D. (35 jugadores)
UPDATE public.jugadores SET equipo_id = 'ca63866d-a7c2-4a92-89a4-3c41f9d963c5'
WHERE (nombre, apellidos) IN (
  ('Alexandru', 'Ilinca Ionut'),
  ('Fernando', 'Sanchez Diaz'),
  ('Francisco Javier', 'Mateo Vera'),
  ('Abdelali', 'Mais Jouhri'),
  ('Aitor', 'Ocaña Romero'),
  ('Alejandro', 'Jimenez Reinaldo'),
  ('Christian', 'Ledesma Gil'),
  ('Diego', 'Gómez Benítez'),
  ('Francisco Javier', 'Moreno Delgado'),
  ('Nestor Nahuel', 'Gastaud'),
  ('Javier', 'Mejías García'),
  ('Lamin', 'Camara'),
  ('Luis Daniel', 'Maitan Sanoja'),
  ('Miguel', 'Navarro Cano'),
  ('Pablo', 'Zarzuela Moreno'),
  ('Zihao', 'Luo'),
  ('Adrián', 'Gómez Dominguez'),
  ('Daniel', 'Jiménez Bandera'),
  ('Domingo', 'Bueno García'),
  ('Francisco Javier', 'Vallecillo Andrades'),
  ('Francisco Javier', 'Barreno Saraiba'),
  ('Iker', 'Moreno Orellana'),
  ('Ismael', 'Ledesma Gil'),
  ('Israel Abraham', 'Barea Báez'),
  ('Itzan', 'Canto Cabello'),
  ('Jose', 'Bernal Cabeza'),
  ('Ernesto', 'Cuenca Heredia'),
  ('Eugenio', 'Cañas Morales'),
  ('Felipe', 'Marchante Santos'),
  ('Joaquin', 'Mariscal García'),
  ('Jose Francisco', 'Gomez Reinaldo'),
  ('Juan Antonio', 'Rojas Nuñez'),
  ('Rubén', 'Rojas Mejías'),
  ('Sidiki', 'Therna Mara'),
  ('Anthonie Ronald Pepijn', 'Van Der Wissel')
);

-- Migración 028: ALGECIRAS C.F. (30 jugadores)
UPDATE public.jugadores SET equipo_id = 'e22a9e91-b62c-48e3-9fd3-e4c19ff80208'
WHERE (nombre, apellidos) IN (
  ('Daniel', 'Sánchez Pérez'),
  ('Manuel', 'Mármol Martin'),
  ('Diego Alejandro', 'Angulo Sinisterra'),
  ('George Gustave', 'Pezzeca'),
  ('Hugo', 'Losada Núñez'),
  ('Jairo', 'Rubio Aguera'),
  ('Jesús', 'Heredia Lima'),
  ('Rafael', 'Arroyo Castro'),
  ('Santiago', 'Bustos Escobar'),
  ('Adrián', 'Martínez Torres'),
  ('Alejandro', 'Vega Melgar'),
  ('Álvaro', 'Ruiz Benitez'),
  ('Cristian', 'León Aguilera'),
  ('Javier', 'Benítez España'),
  ('Francisco Jorge', 'Martínez Montes'),
  ('Louay', 'Bakkali Yettefti'),
  ('Rafael', 'Febles Benítez'),
  ('Samuel', 'Espinosa Garcia'),
  ('José', 'Varela Alcaraz'),
  ('Washington', 'Rosero Loango'),
  ('Adam', 'Riani'),
  ('Alvaro', 'Aguado Delgado'),
  ('Álvaro', 'Valverde Medero'),
  ('Daniel', 'Recagno Guerrero'),
  ('Gerardo', 'Clavijo Alba'),
  ('Iván', 'Mayayo Cano'),
  ('Manuel', 'González Velasco'),
  ('Martín', 'Córdoba Mora'),
  ('Pablo', 'Velasco Jiménez'),
  ('Simón', 'Rodriguez Marenghi')
);

-- Migración 029: A.D. NUEVA JARILLA (22 jugadores)
UPDATE public.jugadores SET equipo_id = '1cc6683d-952c-40db-83e1-caf6f938894b'
WHERE (nombre, apellidos) IN (
  ('Alejandro', 'Martínez Rosado'),
  ('Juan Jose', 'Peña Mateos'),
  ('Pablo', 'Abuín Casado'),
  ('Adahy', 'Jiménez Sánchez'),
  ('Alejandro', 'Perez Calvo De La Rosa'),
  ('Antonio', 'Cebrian Sanchez'),
  ('Francisco Javier', 'Conde Nieves'),
  ('Gabriel', 'Becerra Garcia'),
  ('Angel', 'Gallero Prat'),
  ('Ismael', 'Gonzalez Grimaldi'),
  ('Juan', 'Laynez García'),
  ('Sergio', 'Montalvo Vega'),
  ('Alejandro', 'Bautista Gil'),
  ('Alejandro', 'Castillo Garrido'),
  ('Cristian', 'Fernandez Lopez'),
  ('Ezequiel', 'Acuña Reguera'),
  ('Isaac', 'Garrido Fernandez'),
  ('Alejandro', 'Montalvo Vega'),
  ('Sergio', 'Puche Campuzano'),
  ('Adrian', 'Escalera Caballero'),
  ('Manuel', 'Gutierrez Heredia'),
  ('Juan Luis', 'Fernández Pérez')
);

-- ============================================================
-- VERIFICACIÓN FINAL
-- ============================================================

-- Contar jugadores por equipo tras las actualizaciones
SELECT 
  e.nombre as "Equipo",
  COUNT(j.id) as "Jugadores asignados",
  ROUND(SUM(j.precio)::numeric /1000000, 2) as "Presupuesto (M€)"
FROM public.equipos_reales e
LEFT JOIN public.jugadores j ON j.equipo_id = e.id
WHERE e.division = 'segunda_andaluza'
GROUP BY e.id, e.nombre
ORDER BY e.created_at;

-- Total consolidado
SELECT 
  COUNT(*) as "Total jugadores asignados",
  ROUND(SUM(precio)::numeric / 1000000, 2) as "Presupuesto total (M€)"
FROM public.jugadores;
