-- ============================================================
-- Fantasy Andalucía — Migración 022: Equipo U.D. TESORILLO
-- Actualizar equipo_id de 46 jugadores de U.D. TESORILLO
-- ============================================================

UPDATE public.jugadores SET equipo_id = 'fb374d39-3883-46ee-8af1-88b61f22bdaa'
WHERE (nombre, apellidos) IN (
  ('Álvaro', 'Torres Sánchez'),
  ('David', 'Mena Maldonado'),
  ('Juan', 'Ruiz Sánchez'),
  ('Alejandro', 'Troya López'),
  ('Yeray', 'Espada Bañasco'),
  ('Bachir', 'Bennor Selva'),
  ('Javier', 'Collado Sarría'),
  ('Federico', 'Guerreiro Martín'),
  ('Juan', 'García Rodríguez'),
  ('Álvaro', 'Caballero Vilches'),
  ('Hector', 'Sadobe'),
  ('Jorge', 'Domínguez García'),
  ('Salvador', 'Mesa Sánchez'),
  ('Diego', 'González Pachón'),
  ('Juan', 'Rubio Manzano'),
  ('Enrique', 'del Alcázar Delgado'),
  ('Alvaro', 'Requena Mena'),
  ('Sergio', 'Tirado Sánchez'),
  ('Alberto', 'Lopez Morilla'),
  ('Alioune', 'Ndiaye Gonzalez'),
  ('Ignacio', 'Caballero Ginés'),
  ('Cristian', 'Guerrero Alconchel'),
  ('José', 'Alamino Segovia'),
  ('David', 'Mancera Garcia'),
  ('Miguel', 'Salas Gavira'),
  ('Francisco', 'Moreno Donda'),
  ('Pablo', 'Torres Lobato'),
  ('Pedro', 'Martin Mateo'),
  ('Juan', 'Reine Pérez'),
  ('Sergiu', 'Marian Oprea'),
  ('José', 'González Morales'),
  ('Adrián', 'Rodríguez Rodríguez'),
  ('Antonio', 'Aguirre Aguirre'),
  ('Fernando', 'Cuesta Bakouri'),
  ('Ibrahim', 'Khbiyez Laariara'),
  ('Isaac', 'Pérez Macías'),
  ('Jacob', 'Arguello Ubillus'),
  ('Juan', 'Romero Gil'),
  ('Sergio', 'Ginés Pérez'),
  ('Lorenzo', 'Micha Eyang'),
  ('Manuel', 'Marín Barranco'),
  ('Francisco', 'Rios Rivera'),
  ('Francisco', 'Pérez Cano'),
  ('Abrahan', 'Marchante Gómez'),
  ('Roberto', 'Nahuel Mena'),
  ('Sadek', 'Sadek Mohamed')
);
